#!/bin/bash
#
# test simple command /bin/pwd

# load funtion definitions
. ../functions.sh

command="/bin/pwd"
output_file="test_output_file_$RANDOM"

printf "########## INIT TEST ##########\n"

# run command
printf "executing command $command and saving in $output_file ...\n"
sleep 3
echo "$command" | $SHELL > $output_file 2> /dev/null
printf "done!\n"

# wait a little bit
$SLEEP $SLEEPSECONDS

# check the result
printf "checking if current directory's path is listed in $output_file ...\n"
sleep 3
nmatch=`cat $output_file | grep -c "$(echo $PWD)"`
if [ $nmatch -eq 1 ]; then
	   print_ok
else
	   print_ko
	rm -f $tmp_file
	rm -f $output_file
	printf "Something went wrong. [\033[31mPlease fix it.\033[37m]\n"
	stop_shell
fi

# wait a little bit again before clean
$SLEEP $SLEEPSECONDS

printf "removing files ...\n"
sleep 3
# clean up
rm -f $output_file
printf "\033[32mdone!\033[37m\n"
printf "########## END TEST ##########\n"
