#!/bin/bash
#
# test simple command /bin/ls

# load funtion definitions
. ../functions.sh

command="/bin/pwd"
output_file="test_output_file_$RANDOM"

# run command
echo "$command" | $SHELL > $output_file 2> /dev/null

# wait a little bit
$SLEEP $SLEEPSECONDS

# check the result
nmatch=`cat $output_file | grep -c "$(echo $PWD)"`
if [ $nmatch -eq 1 ]; then
	   print_ok
else
	   print_ko
fi

# wait a little bit again before clean
$SLEEP $SLEEPSECONDS

# clean up
rm -f $output_file
